name: Generate profile metrics
on:
  schedule:
    - cron: "17 5,17 * * *"   # updates ~2x/day
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ChrisLaFumee
          template: classic
          config_timezone: America/New_York

          # Core sections
          base: header, activity, repositories, metadata

          # Streak + calendar (100-Day challenge friendly)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_streak: yes

          # Coding habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Languages & achievements
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_display: compact
